defaults:
  - _self_
  - hydra: default
  - datamodule: 3dpw
  - model: prediction_model
  - net: t2p_jrdb
output: 3dpw_t2p

is_baseline: False
desc: debug
seed: 1234
monitor: val/JPE_overall_1600ms
save_top_k: 3
viz_traj: True
viz_joint: True
viz_joint_jansang: True
kernel_size: 4
sampling_method: 'ade'
local_radius: 50

input_time: 10
output_time: 20
num_modes: 6
dataset: '3dpw'
num_joints: 13

data_root:
checkpoint: 'D:\Downloads\T2P\T2P-main\outputs\3dpw_t2p\2025-03-25\12-44-50_debug\checkpoints\epoch=54-step=29700.ckpt'
pretrained_weights:

# trainer
#num_workers: 32
num_workers: 0
gpus: 1
sync_bn: true
#batch_size: 64
batch_size: 24
epochs: 60
warmup_epochs: 10


# optimizer
lr: 0.0003
weight_decay: 2
gradient_clip_val: 5
gradient_clip_algorithm: norm

limit_train_batches:
limit_val_batches:
limit_test_batches:
log_model: all
test: true

wandb: disable
