# 默认配置
defaults:
  - _self_
  - hydra: default
  - datamodule: 3dpw
  - model: prediction_model
  - net: t2p
output: 3dpw_t2p

# 基本设置
is_baseline: False # 是否为基线模型
desc: debug # 描述信息
seed: 1234 # 随机种子
monitor: val/JPE_overall_1600ms # 监控指标
save_top_k: 3 # 保存最好的k个模型
viz_traj: True # 是否可视化轨迹
viz_joint: True # 是否可视化关节点
viz_joint_jansang: True # 是否可视化关节点(jansang方式)
kernel_size: 4 # 卷积核大小
sampling_method: "ade" # 采样方法
local_radius: 50 # 局部半径

# 模型参数
# 输入前10帧/时间步，输出后20帧/时间步
input_time: 10 # 输入时间步长
output_time: 20 # 输出时间步长
num_modes: 6 # 模态数量
method: "weighted" # 关节点选择方法
dataset: "3dpw" # 数据集名称
num_joints: 13 # 关节点数量

# 路径配置
data_root: # 数据根目录
checkpoint: 'D:\Downloads\T2P\T2P-main\outputs\3dpw_t2p\weighted\2025-03-29\21-09-20_debug\checkpoints\epoch=41-step=8526.ckpt' # 检查点路径
pretrained_weights: # 预训练权重路径

# 训练器配置
#num_workers: 32  # 数据加载线程数(已注释)
num_workers: 0 # 数据加载线程数
gpus: 1 # GPU数量
sync_bn: true # 是否同步批归一化
# batch_size: 64 # 批次大小
batch_size: 24 # 批次大小(已注释)
epochs: 60 # 训练轮数
warmup_epochs: 10 # 预热轮数

# 优化器配置
lr: 0.0003 # 学习率
weight_decay: 2 # 权重衰减
gradient_clip_val: 5 # 梯度裁剪值
gradient_clip_algorithm: norm # 梯度裁剪算法

# 其他配置
limit_train_batches: # 限制训练批次数
limit_val_batches: # 限制验证批次数
limit_test_batches: # 限制测试批次数
log_model: all # 模型日志记录
test: true # 是否测试

wandb: disable # wandb配置
